version: '3.8'

services:
  vana-personal-server:
    image: opendatalabs/vana-personal-server:release-automation-5b128b1
    container_name: vana-personal-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3