# Production Environment Configuration
# This file documents the expected configuration for production deployments

environment: production
gcp:
  project_id: corsali-production
  region: europe-west1
  service_name: vana-personal-server
  
resources:
  memory: 2Gi
  cpu: 2
  min_instances: 0
  max_instances: 10
  
environment_variables:
  CHAIN_ID: "1480"  # Mainnet chain ID
  
secrets:
  - WALLET_MNEMONIC
  - REPLICATE_API_TOKEN