name: Docker Pre-release

on:
  push:
    branches:
      - 'feat/**'
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/prerelease.yml'

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SERVICE_ACCOUNT_PAT }}

      - name: Extract branch name and set tags
        id: meta
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          # Replace / with - for Docker tag compatibility
          SAFE_BRANCH=$(echo $BRANCH_NAME | sed 's/\//-/g')
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Set Docker tags
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "vanaorg/vana-personal-server:${SAFE_BRANCH}" >> $GITHUB_OUTPUT
          echo "vanaorg/vana-personal-server:${SAFE_BRANCH}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "Branch: $BRANCH_NAME"
          echo "Docker tags: ${SAFE_BRANCH}, ${SAFE_BRANCH}-${SHORT_SHA}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            COMMIT_SHA=${{ github.sha }}